linters:
  enable:
    - gosec
    - godot
    - misspell
    - stylecheck


linters-settings:
  stylecheck:
    checks: ["all", "ST1*"]

issues:
  exclude-use-default: false

output:
  # print lines of code with issue, default is true
  print-issued-lines: false
  # print linter name in the end of issue text, default is true
  print-linter-name: true

